env:
  BACKBLAZE_APP_KEY_ID: ENCRYPTED[95a37d7a31679c7fb32b03d05b33edb065dcf7f0f823e7fe721e3247e5f3668d4063591d5c733ade1fd7a32f5f859c5f]
  BACKBLAZE_APP_KEY: ENCRYPTED[770e70e48569f43396e50d0692a4c1abe64e4821c1ef816520c792ad6222c61641b7e56132e37896340f740720196604]

win_machine_build_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019

  choco_script:
    - cinst -y -r git cmake wget tartool make #visualstudio2017community

  docker_vcpkg_test_script:
    - vcpkg version

  # vcpkg_script:
  #   - git clone https://github.com/Microsoft/vcpkg.git
  #   - cd vcpkg
  #   - ps: .\bootstrap-vcpkg.bat
  #   - ps: .\vcpkg integrate install

  # deps_script:
  #   - cd vcpkg
  #   - .\vcpkg install libsndfile libflac libvorbis libogg spdlog

  nuget_install_script:
    - ps: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"
    - ps: Install-PackageProvider -Name "Nuget" -MinimumVersion "2.8.5.216" -Force

  nuget_script:
    - ps: Install-Package libsndfile-msvc-x64
    - ps: Install-Package FLAC.WindowsRuntime
    - ps: Install-Package vorbis-msvc-x64
    - ps: Install-Package libogg
    - ps: Install-Package spdlog.native

  lame_download_script:
    - ps: wget https://netix.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
    - ps: tartool xf lame-3.100.tar.gz ./
    - cd lame-3.100
    - ./configure --disable-decoder --disable-shared --enable-static
    - make -j4
    - make install

  rtaudio_download_script:
    - ps: wget http://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-5.1.0.tar.gz
    - ps: tartool xf rtaudio-5.1.0.tar.gz ./
    - cd rtaudio-5.1.0
    - mkdir -p __build && cd __build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake
    - cmake --build .
    - cmake --install .

  build_script:
    - mkdir -p __build
    - cd __build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake
    - cmake --build . -v

  package_artifacts:
    path: __build

publish_task:
  container:
    image: gcc:latest

  depends_on:
    - linux_build
    - win_build
  only_if: $CIRRUS_BRANCH == 'master'
  publish_script:
    - apt update && apt install python python-pip -y
    - pip install b2
    - chmod +x .ci/*.sh
    - b2 authorize-account $BACKBLAZE_APP_KEY_ID $BACKBLAZE_APP_KEY
    - .ci/chronicle-b2-upload.sh
