SET(CMAKE_SYSTEM_NAME Windows)

if (${COMPILER_TRIPLET} STREQUAL "x86_64-w64-mingw32")
    set(CMAKE_SYSTEM_PROCESSOR AMD64)
else ()
    set(CMAKE_SYSTEM_PROCESSOR x86)
endif()

include(CMakeForceCompiler)

set(CMAKE_C_COMPILER /usr/bin/${COMPILER_TRIPLET}-gcc-posix)
set(CMAKE_CXX_COMPILER /usr/bin/${COMPILER_TRIPLET}-g++-posix)
set(CMAKE_PREFIX_PATH /usr/${COMPILER_TRIPLET})

SET(BOOST_ROOT /usr/${COMPILER_TRIPLET}/include/boost-1_68)
SET(BOOST_LIBRARYDIR /usr/${COMPILER_TRIPLET}/lib)

if (${COMPILER_TRIPLET} STREQUAL "x86_64-w64-mingw32")
    set(Boost_ARCHITECTURE "-x64")
else ()
    set(Boost_ARCHITECTURE "-i686")
endif()

set(Boost_USE_DEBUG_RUNTIME OFF)

SET(CMAKE_FIND_ROOT_PATH /usr/${COMPILER_TRIPLET} /usr/${COMPILER_TRIPLET}/include/boost-1_68)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)